### ISSUE TITLE
Parsing fails for defines as keys in case statement

### ISSUE THREAD

**Issue by micprog** [zarubaf/morty#24] opened 2020-12-17 14:00 UTC
Parsing of sv source files fails for blocks that contain a case statement, where the keys are defines. To highlight a few examples that fail from the pulp-platform: 
https://github.com/pulp-platform/apb_adv_timer/blob/master/rtl/adv_timer_apb_if.sv
https://github.com/pulp-platform/apb_gpio/blob/master/rtl/apb_gpio.sv
https://github.com/pulp-platform/udma_core/blob/master/rtl/common/udma_ctrl.sv

Is this behaviour intentional?

**Comment by zarubaf** [comment] 2020-12-17 14:38
The problem is actually the comment behind the define. So in the preprocessor step, the define is taken until the new line and replaced verbatim. That adds the comment which potentially leads to unbalanced expressions and unparseable SystemVerilog.

Tbh, I haven't checked with the standard whether this behavior is correct or the comment should be stripped from the define. Maybe you want to check or @fabianschuiki knows more?

**Comment by fabianschuiki** [comment] 2020-12-17 15:09
That's a good question. The standard is extremely vague about how exactly the preprocessing is supposed to work. I have a feeling that most commercial tools would just read the define up to the comment, and then treat the comment separately (and not part of the define). Or they expand uses of the define with the tokens already isolated, such that the comment is just another symbol and does not poison stuff after it. But since you can also concatenate defines, I'm pretty sure it's the former approach.

**Comment by zarubaf** [comment] 2021-02-04 10:14
Should be fixed in `v0.5.2`

**Closed by zarubaf** 2021-02-04 10:14 UTC
